---
- name: Ensures watchtower dir exists
  file:
    path: "{{ watchtower_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Adding docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ watchtower_dir }}/docker-compose.yml"
    mode: 0600
    owner: "{{ user }}"
    group: "{{ group }}"